version: "3.9"

services:
  knowlegebase:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports:
      - 8002:8000
    environment:
      - CHATBOT_KNOWLEDGEBASE_STAGE=prod
      - API_KEY=
      - ALG=
      - QDRANT_HOST=172.17.0.1
      - QDRANT_PORT=6333
      - QDRANT_GRPC_PORT=6334
      - QDRANT_USE_HTTPS=false
      - OPENAI_API_KEY=
      - MODEL=gpt-3.5-turbo
      - COLLECTIONS=["index"]




